title: Jralvarezjimenez
author: Juan Alvarez
email: jralvarezjimenez@befun.com
description: Mensaje de prueba, y verificando como aparece.
theme: minima
# social links
twitter_username: befunoficial
github_username:  befunoficial

show_excerpts: false # set to false to remove excerpts on the homepage
